spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true

  devtools:
    add-properties: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  servlet:
    context-path: /api/v1
logging:
  level:
    org:
      hibernate:
#        type: trace
    web: debug
#    sql: trace

#    logging.level.org.hibernate.SQL=DEBUG
#    logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE