spring:
  datasource:
    url: jdbc:mysql://bcc30ec79fd366:5d2081cf@us-cdbr-east-06.cleardb.net/heroku_3b6d84a2153e3de?reconnect=true
    username: bcc30ec79fd366
    password: 5d2081cf
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: true